# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 209ca866408f6c2f596e9f2b055300e48a5a0aa9794a9815d7ef65f30be791a2ef8f8b6405a288e84b0c60a8050c712cfe104f740a88265b60714c1ed7e6986c

test:
  secret_key_base: e6f18e5774ab650d306cde18f1ed943685ecc782c9d068a54ea436ef4bb7ecaefa22d0532c083ae5de3034e4dd6606b6f26cb7c412d98687c44eb2d8cec2d5d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
